-- Historical reconciliation generated by Prisma migrate diff from a clean
-- database with all preceding committed migrations applied to the current
-- committed Prisma schema. It records schema changes that previously existed
-- only outside migration history.
--
-- Compatibility: do not execute this migration blindly on a populated
-- environment that received those changes out of band. First compare that
-- environment with prisma/schema.prisma. If it already matches, review and
-- baseline this migration as applied; otherwise create an environment-specific
-- migration and data-preservation plan.
--
-- HRLetterRequest.fileKey is intentionally retained. Historical databases may
-- contain artifact references in that nullable column. Prisma maps it as the
-- deprecated legacyFileKey field until a separately approved archive/backfill
-- and contract migration proves that removal is safe.

-- AlterTable
ALTER TABLE "ChaDocumentRequirementItem" ALTER COLUMN "acceptedFileTypes" DROP DEFAULT,
ALTER COLUMN "notificationRoles" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ChaExpenseRequest" ALTER COLUMN "status" SET DEFAULT 'UNDER_REVIEW';

-- AlterTable
ALTER TABLE "ChaJob" ADD COLUMN     "assignedManagerId" TEXT,
ADD COLUMN     "estimatedClosureDate" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "ChaJobAdditionalData" ADD COLUMN     "doDocumentFileKey" TEXT,
ADD COLUMN     "doDocumentFileName" TEXT,
ADD COLUMN     "doDocumentUploadedAt" TIMESTAMP(3),
ADD COLUMN     "doDocumentUploadedById" TEXT,
ADD COLUMN     "doExtensionEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "doUploadEnabled" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "ChaSettings" ADD COLUMN     "jobCreatorUsers" JSONB,
ADD COLUMN     "jobNumberNextNum" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "jobNumberPrefix" TEXT NOT NULL DEFAULT 'CHA';

-- AlterTable
ALTER TABLE "FilingChecklistItem" ALTER COLUMN "acceptedFileTypes" DROP DEFAULT,
ALTER COLUMN "notificationRoles" DROP DEFAULT;

-- AlterTable
ALTER TABLE "FilingPhotoRequirement" ALTER COLUMN "notificationRoles" DROP DEFAULT;

-- AlterTable
ALTER TABLE "FilingWorkflowNode" ALTER COLUMN "approvalRoles" DROP DEFAULT;

-- AlterTable
ALTER TABLE "HRLetterRequest" ADD COLUMN     "acceptanceIp" TEXT,
ADD COLUMN     "acceptanceUserAgent" TEXT,
ADD COLUMN     "acceptedAt" TIMESTAMP(3),
ADD COLUMN     "auditTrail" JSONB,
ADD COLUMN     "counterSignIp" TEXT,
ADD COLUMN     "counterSignedAt" TIMESTAMP(3),
ADD COLUMN     "counterSignedById" TEXT,
ADD COLUMN     "documentHash" TEXT,
ADD COLUMN     "docxPath" TEXT,
ADD COLUMN     "expiresAt" TIMESTAMP(3),
ADD COLUMN     "issuedAt" TIMESTAMP(3),
ADD COLUMN     "issuedById" TEXT,
ADD COLUMN     "letterNumber" TEXT NOT NULL,
ADD COLUMN     "parentLetterId" TEXT,
ADD COLUMN     "pdfPath" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL,
ALTER COLUMN "status" SET DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE "HRLetterTemplate" ADD COLUMN     "editorDocument" JSONB,
ADD COLUMN     "fieldSchema" JSONB,
ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isLegalReviewed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "legalReviewedAt" TIMESTAMP(3),
ADD COLUMN     "legalReviewedById" TEXT,
ADD COLUMN     "previewHtml" TEXT,
ADD COLUMN     "sourceDocxPath" TEXT,
ADD COLUMN     "sourceFileName" TEXT,
ADD COLUMN     "type" TEXT NOT NULL,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL,
ADD COLUMN     "version" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "OnDutyRequest" ADD COLUMN     "approvedAt" TIMESTAMP(3),
ADD COLUMN     "attachmentUrl" TEXT,
ADD COLUMN     "clientReference" TEXT,
ADD COLUMN     "completedAt" TIMESTAMP(3),
ADD COLUMN     "endLocation" JSONB,
ADD COLUMN     "endTime" TEXT,
ADD COLUMN     "purpose" TEXT,
ADD COLUMN     "rejectedReason" TEXT,
ADD COLUMN     "remarks" TEXT,
ADD COLUMN     "routeSummary" JSONB,
ADD COLUMN     "startLocation" JSONB,
ADD COLUMN     "startTime" TEXT,
ADD COLUMN     "startedAt" TIMESTAMP(3),
ADD COLUMN     "totalDistanceKm" DOUBLE PRECISION,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL,
ADD COLUMN     "visitAddress" TEXT,
ADD COLUMN     "visitLocation" TEXT;

-- AlterTable
ALTER TABLE "Organisation" ADD COLUMN     "crmCallRetentionDays" INTEGER NOT NULL DEFAULT 90;

-- AlterTable
ALTER TABLE "UserSession" ADD COLUMN     "device" TEXT,
ADD COLUMN     "expiresAt" TIMESTAMP(3),
ADD COLUMN     "ipHash" TEXT,
ADD COLUMN     "rememberMe" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "revokeReason" TEXT,
ADD COLUMN     "revokedAt" TIMESTAMP(3),
ADD COLUMN     "revokedById" TEXT;

-- CreateTable
CREATE TABLE "HRLetterSetting" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "numberingPattern" TEXT NOT NULL DEFAULT 'ME/HR/{year}/{seq}',
    "probationDaysDefault" INTEGER NOT NULL DEFAULT 90,
    "noticePeriodDaysDefault" INTEGER NOT NULL DEFAULT 30,
    "letterValidityDaysDefault" INTEGER NOT NULL DEFAULT 7,
    "legalJurisdiction" TEXT NOT NULL DEFAULT 'Chennai, Tamil Nadu',
    "complianceVersion" TEXT NOT NULL DEFAULT '2026.1',
    "signatoryName" TEXT NOT NULL DEFAULT 'HR Manager',
    "signatoryDesignation" TEXT NOT NULL DEFAULT 'Manager - HR',
    "signatorySignatureUrl" TEXT,
    "companySealUrl" TEXT,
    "emailTemplate" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HRLetterSetting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CrmCallAttempt" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "leadId" TEXT NOT NULL,
    "salespersonId" TEXT NOT NULL,
    "customerPhone" TEXT NOT NULL,
    "callStartedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "callEndedAt" TIMESTAMP(3),
    "durationSeconds" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CrmCallAttempt_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CrmCallRecording" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "callAttemptId" TEXT NOT NULL,
    "leadId" TEXT NOT NULL,
    "salespersonId" TEXT NOT NULL,
    "customerPhone" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "filePath" TEXT,
    "fileData" TEXT,
    "durationSeconds" DOUBLE PRECISION NOT NULL,
    "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "sha256Hash" TEXT NOT NULL,
    "matchConfidence" DOUBLE PRECISION NOT NULL,
    "matchReason" TEXT,
    "uploadStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "uploadProgress" INTEGER NOT NULL DEFAULT 0,
    "errorMessage" TEXT,
    "transcriptionStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CrmCallRecording_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CrmCallTranscript" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "recordingId" TEXT NOT NULL,
    "transcriptText" TEXT NOT NULL,
    "summary" TEXT,
    "objections" TEXT,
    "followUpActions" TEXT,
    "sentiment" TEXT,
    "qualityScore" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CrmCallTranscript_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CrmCallReview" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "recordingId" TEXT NOT NULL,
    "reviewerId" TEXT NOT NULL,
    "rating" INTEGER NOT NULL,
    "comments" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CrmCallReview_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CrmCallRecordingAuditLog" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "recordingId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CrmCallRecordingAuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GoogleWorkspaceConnection" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "googleEmail" TEXT NOT NULL,
    "googleUserId" TEXT NOT NULL,
    "accessToken" TEXT NOT NULL,
    "refreshToken" TEXT NOT NULL,
    "tokenExpiresAt" TIMESTAMP(3) NOT NULL,
    "scopes" TEXT[],
    "status" TEXT NOT NULL DEFAULT 'connected',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GoogleWorkspaceConnection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GoogleWorkspaceSetting" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "workspaceDomain" TEXT NOT NULL DEFAULT 'adarshshipping.in',
    "automationUser" TEXT NOT NULL DEFAULT 'no-reply@adarshshipping.in',
    "sharedDriveId" TEXT,
    "jobsRootFolderId" TEXT,
    "jobSpaceNamingTemplate" TEXT NOT NULL DEFAULT 'JOB-{jobNumber} | {customerName} | {serviceName}',
    "jobFolderTemplate" JSONB,
    "pubSubTopic" TEXT,
    "pubSubSubscription" TEXT,
    "webhookAudience" TEXT,
    "enableGoogleChatLiveView" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GoogleWorkspaceSetting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CommunicationAuditEvent" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "details" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CommunicationAuditEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ChaTeamGroup" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "memberIds" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ChaTeamGroup_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ChaDoExtension" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "previousValidity" TIMESTAMP(3),
    "extensionDate" TIMESTAMP(3) NOT NULL,
    "fileKey" TEXT,
    "fileName" TEXT,
    "appliedById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ChaDoExtension_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitSetting" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "candidateNumberFormat" TEXT NOT NULL DEFAULT 'RC-{year}-{seq}',
    "applicationNumberFormat" TEXT NOT NULL DEFAULT 'APP-{year}-{seq}',
    "retentionDays" INTEGER NOT NULL DEFAULT 730,
    "consentText" TEXT,
    "maxResumeSizeBytes" INTEGER NOT NULL DEFAULT 10485760,
    "allowedResumeTypes" TEXT[] DEFAULT ARRAY['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']::TEXT[],
    "duplicateCheckEmail" BOOLEAN NOT NULL DEFAULT true,
    "duplicateCheckPhone" BOOLEAN NOT NULL DEFAULT true,
    "duplicateCheckResumeHash" BOOLEAN NOT NULL DEFAULT true,
    "duplicateCheckProfileUrl" BOOLEAN NOT NULL DEFAULT true,
    "aiProvider" TEXT NOT NULL DEFAULT 'openai',
    "aiModel" TEXT NOT NULL DEFAULT 'gpt-4o',
    "aiPromptVersion" TEXT NOT NULL DEFAULT 'v1',
    "automationBatchSize" INTEGER NOT NULL DEFAULT 50,
    "jobSeekerEnabled" BOOLEAN NOT NULL DEFAULT true,
    "allowedJobProviders" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "shareExpiryDays" INTEGER NOT NULL DEFAULT 7,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitSetting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitJobOpening" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "internalCode" TEXT,
    "title" TEXT NOT NULL,
    "departmentId" TEXT,
    "designationText" TEXT,
    "branchId" TEXT,
    "location" TEXT,
    "employmentType" TEXT NOT NULL DEFAULT 'FULL_TIME',
    "workplaceType" TEXT NOT NULL DEFAULT 'ONSITE',
    "openings" INTEGER NOT NULL DEFAULT 1,
    "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "targetJoiningDate" DATE,
    "hiringManagerId" TEXT,
    "experienceMin" DOUBLE PRECISION,
    "experienceMax" DOUBLE PRECISION,
    "educationRequired" TEXT,
    "mandatorySkills" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "preferredSkills" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "responsibilities" TEXT,
    "compensationMin" DOUBLE PRECISION,
    "compensationMax" DOUBLE PRECISION,
    "compensationCcy" TEXT NOT NULL DEFAULT 'INR',
    "sourcingChannels" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "closingDate" DATE,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "jobDescriptionHtml" TEXT,
    "requirementsJson" JSONB,
    "screeningQuestions" JSONB,
    "interviewPlanJson" JSONB,
    "approvalFlowJson" JSONB,
    "publishedAt" TIMESTAMP(3),
    "closedAt" TIMESTAMP(3),
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdById" TEXT NOT NULL,
    "updatedById" TEXT,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitJobOpening_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitJobVersion" (
    "id" TEXT NOT NULL,
    "jobOpeningId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "changeType" TEXT NOT NULL,
    "snapshotJson" JSONB NOT NULL,
    "changedById" TEXT NOT NULL,
    "changedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitJobVersion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitCandidate" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "candidateNumber" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "currentLocation" TEXT,
    "preferredLocation" TEXT,
    "currentCompany" TEXT,
    "currentTitle" TEXT,
    "totalExperienceYears" DOUBLE PRECISION,
    "relevantExpYears" DOUBLE PRECISION,
    "noticePeriodDays" INTEGER,
    "currentCompensation" DOUBLE PRECISION,
    "expectedCompensation" DOUBLE PRECISION,
    "compensationCcy" TEXT NOT NULL DEFAULT 'INR',
    "skills" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "workAuthorization" TEXT,
    "source" TEXT,
    "sourceDetail" TEXT,
    "consentStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "consentAt" TIMESTAMP(3),
    "consentIp" TEXT,
    "retentionDeadline" DATE,
    "legalHold" BOOLEAN NOT NULL DEFAULT false,
    "deletedAt" TIMESTAMP(3),
    "anonymizedAt" TIMESTAMP(3),
    "resumeHash" TEXT,
    "profileUrlHash" TEXT,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "customFields" JSONB,
    "ownerUserId" TEXT,
    "createdById" TEXT NOT NULL,
    "updatedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitCandidate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitCandidateConsent" (
    "id" TEXT NOT NULL,
    "candidateId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "consentText" TEXT NOT NULL,
    "ip" TEXT,
    "userAgent" TEXT,
    "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitCandidateConsent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitCandidateResume" (
    "id" TEXT NOT NULL,
    "candidateId" TEXT NOT NULL,
    "fileKey" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "resumeHash" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "parsedStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "parsedJson" JSONB,
    "parserProvider" TEXT,
    "parserVersion" TEXT,
    "parseConfidence" DOUBLE PRECISION,
    "parseError" TEXT,
    "confirmedAt" TIMESTAMP(3),
    "confirmedById" TEXT,
    "uploadedById" TEXT NOT NULL,
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitCandidateResume_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitCandidateEducation" (
    "id" TEXT NOT NULL,
    "candidateId" TEXT NOT NULL,
    "institution" TEXT NOT NULL,
    "degree" TEXT,
    "field" TEXT,
    "startYear" INTEGER,
    "endYear" INTEGER,
    "grade" TEXT,
    "isConfirmed" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "RecruitCandidateEducation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitCandidateExperience" (
    "id" TEXT NOT NULL,
    "candidateId" TEXT NOT NULL,
    "company" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "startDate" DATE,
    "endDate" DATE,
    "isCurrent" BOOLEAN NOT NULL DEFAULT false,
    "description" TEXT,
    "isConfirmed" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "RecruitCandidateExperience_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitCandidateSkill" (
    "id" TEXT NOT NULL,
    "candidateId" TEXT NOT NULL,
    "skill" TEXT NOT NULL,
    "level" TEXT,
    "isConfirmed" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "RecruitCandidateSkill_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitApplication" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "applicationNumber" TEXT NOT NULL,
    "jobOpeningId" TEXT NOT NULL,
    "candidateId" TEXT NOT NULL,
    "stage" TEXT NOT NULL DEFAULT 'NEW',
    "source" TEXT,
    "resumeVersionId" TEXT,
    "submissionSnapshotJson" JSONB,
    "concurrencyVersion" INTEGER NOT NULL DEFAULT 1,
    "deletedAt" TIMESTAMP(3),
    "createdById" TEXT NOT NULL,
    "updatedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitApplication_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitApplicationStageHistory" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "fromStage" TEXT,
    "toStage" TEXT NOT NULL,
    "actorId" TEXT NOT NULL,
    "reason" TEXT,
    "metadata" JSONB,
    "movedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitApplicationStageHistory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitScreeningQuestion" (
    "id" TEXT NOT NULL,
    "jobOpeningId" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'TEXT',
    "options" JSONB,
    "required" BOOLEAN NOT NULL DEFAULT false,
    "order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "RecruitScreeningQuestion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitScreeningAnswer" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "questionId" TEXT NOT NULL,
    "answerText" TEXT,
    "answerJson" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitScreeningAnswer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitScreeningRun" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "idempotencyKey" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'QUEUED',
    "triggeredBy" TEXT NOT NULL,
    "triggeredById" TEXT,
    "automationRunId" TEXT,
    "jobReqVersion" INTEGER NOT NULL,
    "resumeVersionId" TEXT,
    "rubricVersion" TEXT NOT NULL,
    "promptVersion" TEXT NOT NULL,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "errorMessage" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitScreeningRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitScreeningResult" (
    "id" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "resumeVersionId" TEXT,
    "overallScore" DOUBLE PRECISION NOT NULL,
    "mandatorySkillScore" DOUBLE PRECISION NOT NULL,
    "preferredSkillScore" DOUBLE PRECISION NOT NULL,
    "experienceScore" DOUBLE PRECISION NOT NULL,
    "educationScore" DOUBLE PRECISION NOT NULL,
    "locationScore" DOUBLE PRECISION NOT NULL,
    "screeningQScore" DOUBLE PRECISION NOT NULL,
    "matchingEvidence" JSONB NOT NULL,
    "missingRequirements" JSONB NOT NULL,
    "uncertainties" JSONB NOT NULL,
    "followUpQuestions" JSONB NOT NULL,
    "summary" TEXT NOT NULL,
    "aiProvider" TEXT NOT NULL,
    "aiModel" TEXT NOT NULL,
    "promptVersion" TEXT NOT NULL,
    "rawOutputJson" JSONB,
    "overrideScore" DOUBLE PRECISION,
    "overrideReason" TEXT,
    "overrideById" TEXT,
    "overrideAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitScreeningResult_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitInterview" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "roundName" TEXT NOT NULL,
    "roundNumber" INTEGER NOT NULL DEFAULT 1,
    "mode" TEXT NOT NULL DEFAULT 'VIDEO',
    "location" TEXT,
    "meetingLink" TEXT,
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    "proposedSlots" JSONB,
    "scheduledAt" TIMESTAMP(3),
    "confirmedAt" TIMESTAMP(3),
    "candidateConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'SCHEDULED',
    "cancelReason" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitInterview_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitInterviewPanel" (
    "id" TEXT NOT NULL,
    "interviewId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'INTERVIEWER',

    CONSTRAINT "RecruitInterviewPanel_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitInterviewFeedback" (
    "id" TEXT NOT NULL,
    "interviewId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "scorecardJson" JSONB NOT NULL,
    "recommendation" TEXT,
    "comments" TEXT,
    "submittedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitInterviewFeedback_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitAssessment" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'WRITTEN',
    "instructions" TEXT,
    "passThreshold" DOUBLE PRECISION,
    "dueDate" DATE,
    "externalRef" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitAssessment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitAssessmentAttempt" (
    "id" TEXT NOT NULL,
    "assessmentId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "score" DOUBLE PRECISION,
    "notes" TEXT,
    "attachments" JSONB,
    "evaluatorId" TEXT,
    "startedAt" TIMESTAMP(3),
    "submittedAt" TIMESTAMP(3),
    "evaluatedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitAssessmentAttempt_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitOffer" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "offerNumber" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "compensationJson" JSONB NOT NULL,
    "proposedJoiningDate" DATE,
    "validUntil" DATE,
    "conditions" TEXT,
    "approvalFlowJson" JSONB,
    "candidateAccessToken" TEXT,
    "candidateTokenExpiry" TIMESTAMP(3),
    "pdfKey" TEXT,
    "docxKey" TEXT,
    "revisionOf" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitOffer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitOfferApproval" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "approverId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "note" TEXT,
    "decidedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitOfferApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitNote" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "candidateId" TEXT,
    "applicationId" TEXT,
    "body" TEXT NOT NULL,
    "isConfidential" BOOLEAN NOT NULL DEFAULT false,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitNote_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitTag" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "candidateId" TEXT,
    "label" TEXT NOT NULL,
    "color" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitTag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitAttachment" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "candidateId" TEXT,
    "applicationId" TEXT,
    "offerId" TEXT,
    "fileKey" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "uploadedById" TEXT NOT NULL,
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitAttachment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitAutomationRun" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "trigger" TEXT NOT NULL,
    "triggeredById" TEXT,
    "status" TEXT NOT NULL DEFAULT 'QUEUED',
    "totalItems" INTEGER NOT NULL DEFAULT 0,
    "doneItems" INTEGER NOT NULL DEFAULT 0,
    "failedItems" INTEGER NOT NULL DEFAULT 0,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "errorSummary" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitAutomationRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitAutomationRunItem" (
    "id" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'QUEUED',
    "errorMessage" TEXT,
    "retryCount" INTEGER NOT NULL DEFAULT 0,
    "processedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitAutomationRunItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitHandoffPackage" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "candidateSnapshot" JSONB NOT NULL,
    "offerSnapshot" JSONB NOT NULL,
    "documentsJson" JSONB NOT NULL,
    "sourceIds" JSONB NOT NULL,
    "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "generatedById" TEXT NOT NULL,

    CONSTRAINT "RecruitHandoffPackage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitAuditEvent" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "actorId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "correlationId" TEXT,
    "changedFields" JSONB,
    "reason" TEXT,
    "source" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitAuditEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitJobSeekerProfile" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "preferredRoles" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "preferredIndustries" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "preferredLocations" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "workplacePreference" TEXT NOT NULL DEFAULT 'ANY',
    "employmentTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "seniority" TEXT,
    "totalExpYears" DOUBLE PRECISION,
    "skills" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "workAuthorization" TEXT,
    "noticePeriodDays" INTEGER,
    "compensationMin" DOUBLE PRECISION,
    "compensationMax" DOUBLE PRECISION,
    "compensationCcy" TEXT NOT NULL DEFAULT 'INR',
    "relocationOpen" BOOLEAN NOT NULL DEFAULT false,
    "excludedCompanies" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "jobKeywords" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "alertsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "alertFrequency" TEXT NOT NULL DEFAULT 'WEEKLY',
    "profileCompleteness" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitJobSeekerProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitJobSearchProfile" (
    "id" TEXT NOT NULL,
    "profileId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "keywords" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "locations" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "workplaceTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "employmentTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "minSalary" DOUBLE PRECISION,
    "maxSalary" DOUBLE PRECISION,
    "resultLimit" INTEGER NOT NULL DEFAULT 20,
    "minMatchScore" DOUBLE PRECISION NOT NULL DEFAULT 60,
    "enabledProviders" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "lastRunAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitJobSearchProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitJobListing" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "externalId" TEXT,
    "canonicalUrl" TEXT,
    "title" TEXT NOT NULL,
    "company" TEXT NOT NULL,
    "location" TEXT,
    "workplaceType" TEXT,
    "employmentType" TEXT,
    "seniority" TEXT,
    "description" TEXT,
    "salaryMin" DOUBLE PRECISION,
    "salaryMax" DOUBLE PRECISION,
    "salaryCcy" TEXT,
    "postedAt" TIMESTAMP(3),
    "expiresAt" TIMESTAMP(3),
    "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "rawProvenance" JSONB,
    "isDismissed" BOOLEAN NOT NULL DEFAULT false,
    "isExpired" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitJobListing_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitSavedJob" (
    "id" TEXT NOT NULL,
    "profileId" TEXT NOT NULL,
    "listingId" TEXT NOT NULL,
    "savedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "notes" TEXT,

    CONSTRAINT "RecruitSavedJob_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitJobMatch" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "searchProfileId" TEXT NOT NULL,
    "listingId" TEXT NOT NULL,
    "overallScore" DOUBLE PRECISION NOT NULL,
    "mandatorySkillMatch" JSONB NOT NULL,
    "missingSkills" JSONB NOT NULL,
    "experienceAlignment" TEXT,
    "locationAlignment" TEXT,
    "compensationAlignment" TEXT,
    "evidence" JSONB,
    "uncertainties" JSONB,
    "suggestedQuestions" JSONB,
    "aiProvider" TEXT,
    "aiModel" TEXT,
    "promptVersion" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitJobMatch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitJobSeekerResume" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "profileId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "fileKey" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "resumeHash" TEXT,
    "isBase" BOOLEAN NOT NULL DEFAULT false,
    "masterProfileJson" JSONB,
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitJobSeekerResume_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitTailoredResume" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "baseResumeId" TEXT NOT NULL,
    "targetListingId" TEXT,
    "targetJobTitle" TEXT,
    "targetCompany" TEXT,
    "diffJson" JSONB,
    "unsupportedClaims" JSONB,
    "ownerApproved" BOOLEAN NOT NULL DEFAULT false,
    "approvedAt" TIMESTAMP(3),
    "docxKey" TEXT,
    "pdfKey" TEXT,
    "aiProvider" TEXT,
    "aiModel" TEXT,
    "promptVersion" TEXT,
    "inputVersion" TEXT,
    "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitTailoredResume_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitCoverLetter" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "baseResumeId" TEXT NOT NULL,
    "targetListingId" TEXT,
    "targetJobTitle" TEXT,
    "targetCompany" TEXT,
    "tone" TEXT NOT NULL DEFAULT 'PROFESSIONAL',
    "lengthPref" TEXT NOT NULL DEFAULT 'MEDIUM',
    "contentText" TEXT,
    "docxKey" TEXT,
    "pdfKey" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "aiProvider" TEXT,
    "aiModel" TEXT,
    "promptVersion" TEXT,
    "ownerApproved" BOOLEAN NOT NULL DEFAULT false,
    "approvedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitCoverLetter_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitJobSeekerApplication" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "profileId" TEXT NOT NULL,
    "listingId" TEXT,
    "internalJobId" TEXT,
    "jobTitle" TEXT NOT NULL,
    "company" TEXT NOT NULL,
    "source" TEXT,
    "applicationUrl" TEXT,
    "resumeVersionId" TEXT,
    "coverLetterId" TEXT,
    "appliedAt" TIMESTAMP(3),
    "privateStatus" TEXT NOT NULL DEFAULT 'INTERESTED',
    "publicStatus" TEXT,
    "followUpDate" DATE,
    "contactPeople" JSONB,
    "compensationNotes" TEXT,
    "ownerNotes" TEXT,
    "submissionConsentGiven" BOOLEAN NOT NULL DEFAULT false,
    "submissionConsentAt" TIMESTAMP(3),
    "consentSnapshotJson" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitJobSeekerApplication_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitJobAlert" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "profileId" TEXT NOT NULL,
    "searchProfileId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "frequency" TEXT NOT NULL DEFAULT 'WEEKLY',
    "deliveryTime" TEXT NOT NULL DEFAULT '09:00',
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    "maxJobs" INTEGER NOT NULL DEFAULT 10,
    "minMatchScore" DOUBLE PRECISION NOT NULL DEFAULT 60,
    "includeSources" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "excludeSources" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "autoTailorResume" BOOLEAN NOT NULL DEFAULT false,
    "emailEnabled" BOOLEAN NOT NULL DEFAULT true,
    "inAppEnabled" BOOLEAN NOT NULL DEFAULT true,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastDeliveredAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitJobAlert_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitCareerConversation" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "profileId" TEXT NOT NULL,
    "title" TEXT,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitCareerConversation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitCareerMessage" (
    "id" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitCareerMessage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitInterviewPrep" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "profileId" TEXT NOT NULL,
    "targetListingId" TEXT,
    "targetJobTitle" TEXT,
    "targetCompany" TEXT,
    "prepPackJson" JSONB NOT NULL,
    "aiProvider" TEXT,
    "aiModel" TEXT,
    "promptVersion" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecruitInterviewPrep_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecruitPrivateShare" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "artifactType" TEXT NOT NULL,
    "artifactId" TEXT NOT NULL,
    "recipientNote" TEXT,
    "purpose" TEXT,
    "token" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "accessCount" INTEGER NOT NULL DEFAULT 0,
    "revokedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecruitPrivateShare_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GoogleChatUserLink" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "orgId" TEXT,
    "googleUserId" TEXT NOT NULL,
    "googleEmail" TEXT,
    "googleDisplayName" TEXT,
    "googleWorkspaceDomain" TEXT,
    "linkStatus" TEXT NOT NULL DEFAULT 'active',
    "verifiedAt" TIMESTAMP(3),
    "linkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastUsedAt" TIMESTAMP(3),
    "revokedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GoogleChatUserLink_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GoogleChatSpace" (
    "id" TEXT NOT NULL,
    "orgId" TEXT,
    "spaceResourceName" TEXT NOT NULL,
    "displayName" TEXT,
    "spaceType" TEXT NOT NULL DEFAULT 'SPACE',
    "botMember" BOOLEAN NOT NULL DEFAULT true,
    "linkedByUserId" TEXT,
    "linkedRecordType" TEXT,
    "linkedRecordId" TEXT,
    "linkedRecordLabel" TEXT,
    "notificationProfile" JSONB,
    "quietHoursStart" TEXT,
    "quietHoursEnd" TEXT,
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    "threadKeys" JSONB,
    "linkStatus" TEXT NOT NULL DEFAULT 'active',
    "lastVerifiedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GoogleChatSpace_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GoogleChatSubscription" (
    "id" TEXT NOT NULL,
    "orgId" TEXT,
    "userId" TEXT,
    "spaceId" TEXT,
    "eventKinds" TEXT[],
    "channel" TEXT NOT NULL DEFAULT 'DM',
    "digestMode" TEXT NOT NULL DEFAULT 'immediate',
    "digestTime" TEXT,
    "minPriority" TEXT NOT NULL DEFAULT 'normal',
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GoogleChatSubscription_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GoogleChatDelivery" (
    "id" TEXT NOT NULL,
    "orgId" TEXT,
    "targetSpaceId" TEXT,
    "targetUserId" TEXT,
    "spaceResourceName" TEXT,
    "notificationId" TEXT,
    "eventKind" TEXT,
    "messageResourceName" TEXT,
    "threadKey" TEXT,
    "threadResourceName" TEXT,
    "idempotencyKey" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'queued',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL DEFAULT 3,
    "lastError" TEXT,
    "nextAttemptAt" TIMESTAMP(3),
    "sentAt" TIMESTAMP(3),
    "payload" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GoogleChatDelivery_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GoogleChatInteractionEvent" (
    "id" TEXT NOT NULL,
    "googleEventId" TEXT NOT NULL,
    "spaceResourceName" TEXT NOT NULL,
    "userResourceName" TEXT,
    "eventType" TEXT NOT NULL,
    "processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GoogleChatInteractionEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GoogleChatLinkToken" (
    "id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "googleUserId" TEXT NOT NULL,
    "googleEmail" TEXT,
    "googleDisplayName" TEXT,
    "spaceResourceName" TEXT,
    "orgId" TEXT,
    "expectedDomain" TEXT,
    "used" BOOLEAN NOT NULL DEFAULT false,
    "usedAt" TIMESTAMP(3),
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GoogleChatLinkToken_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MobileDevice" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "deviceId" TEXT NOT NULL,
    "platform" TEXT NOT NULL DEFAULT 'android',
    "model" TEXT,
    "osVersion" TEXT,
    "appVersion" TEXT,
    "pushToken" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MobileDevice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EmployeeFaceEnrollment" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "enrollmentData" JSONB NOT NULL,
    "enrollmentHash" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "enrolledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "enrolledVia" TEXT NOT NULL DEFAULT 'mobile',
    "resetById" TEXT,
    "resetAt" TIMESTAMP(3),
    "auditTrail" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EmployeeFaceEnrollment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AttendanceSession" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "checkInAt" TIMESTAMP(3) NOT NULL,
    "checkOutAt" TIMESTAMP(3),
    "checkInLocation" JSONB,
    "checkOutLocation" JSONB,
    "checkInFaceVerified" BOOLEAN NOT NULL DEFAULT false,
    "checkOutFaceVerified" BOOLEAN NOT NULL DEFAULT false,
    "checkInFaceConfidence" DOUBLE PRECISION,
    "checkOutFaceConfidence" DOUBLE PRECISION,
    "checkInDeviceId" TEXT,
    "checkOutDeviceId" TEXT,
    "checkInSource" TEXT NOT NULL DEFAULT 'MOBILE',
    "checkOutSource" TEXT,
    "checkInIp" TEXT,
    "checkOutIp" TEXT,
    "trackingEnabled" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "closedReason" TEXT,
    "workingMinutes" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AttendanceSession_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LocationTrackingSession" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "attendanceSessionId" TEXT,
    "onDutyRequestId" TEXT,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "stoppedAt" TIMESTAMP(3),
    "intervalMinutes" INTEGER NOT NULL DEFAULT 60,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "stopReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LocationTrackingSession_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LocationPoint" (
    "id" TEXT NOT NULL,
    "trackingSessionId" TEXT NOT NULL,
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,
    "accuracy" DOUBLE PRECISION,
    "altitude" DOUBLE PRECISION,
    "speed" DOUBLE PRECISION,
    "bearing" DOUBLE PRECISION,
    "timestamp" TIMESTAMP(3) NOT NULL,
    "batteryLevel" DOUBLE PRECISION,
    "deviceId" TEXT,
    "networkStatus" TEXT,
    "source" TEXT NOT NULL DEFAULT 'HOURLY',
    "isMocked" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LocationPoint_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TrackingAlert" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "trackingSessionId" TEXT,
    "onDutyRequestId" TEXT,
    "alertType" TEXT NOT NULL,
    "lastKnownLat" DOUBLE PRECISION,
    "lastKnownLng" DOUBLE PRECISION,
    "lastUpdateAt" TIMESTAMP(3),
    "message" TEXT,
    "resolvedAt" TIMESTAMP(3),
    "notifiedManagerId" TEXT,
    "notifiedAdminId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TrackingAlert_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FuelReimbursementPolicy" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "ratePerKm" DOUBLE PRECISION NOT NULL DEFAULT 3.75,
    "currency" TEXT NOT NULL DEFAULT 'INR',
    "effectiveFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "effectiveTo" TIMESTAMP(3),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FuelReimbursementPolicy_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FuelReimbursementClaim" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "onDutyRequestId" TEXT NOT NULL,
    "distanceKm" DOUBLE PRECISION NOT NULL,
    "ratePerKm" DOUBLE PRECISION NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "approvedById" TEXT,
    "approvedAt" TIMESTAMP(3),
    "rejectedReason" TEXT,
    "paidAt" TIMESTAMP(3),
    "paidById" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FuelReimbursementClaim_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserAgreementVersion" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "contentHash" TEXT NOT NULL,
    "effectiveFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserAgreementVersion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserAgreementAcceptance" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "agreementVersionId" TEXT NOT NULL,
    "acceptedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ipAddress" TEXT,
    "deviceId" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserAgreementAcceptance_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "HRLetterSetting_orgId_key" ON "HRLetterSetting"("orgId");

-- CreateIndex
CREATE INDEX "CrmCallAttempt_orgId_idx" ON "CrmCallAttempt"("orgId");

-- CreateIndex
CREATE INDEX "CrmCallAttempt_leadId_idx" ON "CrmCallAttempt"("leadId");

-- CreateIndex
CREATE INDEX "CrmCallAttempt_salespersonId_idx" ON "CrmCallAttempt"("salespersonId");

-- CreateIndex
CREATE UNIQUE INDEX "CrmCallRecording_callAttemptId_key" ON "CrmCallRecording"("callAttemptId");

-- CreateIndex
CREATE UNIQUE INDEX "CrmCallRecording_sha256Hash_key" ON "CrmCallRecording"("sha256Hash");

-- CreateIndex
CREATE INDEX "CrmCallRecording_orgId_idx" ON "CrmCallRecording"("orgId");

-- CreateIndex
CREATE INDEX "CrmCallRecording_leadId_idx" ON "CrmCallRecording"("leadId");

-- CreateIndex
CREATE INDEX "CrmCallRecording_salespersonId_idx" ON "CrmCallRecording"("salespersonId");

-- CreateIndex
CREATE UNIQUE INDEX "CrmCallTranscript_recordingId_key" ON "CrmCallTranscript"("recordingId");

-- CreateIndex
CREATE INDEX "CrmCallTranscript_orgId_idx" ON "CrmCallTranscript"("orgId");

-- CreateIndex
CREATE INDEX "CrmCallReview_orgId_idx" ON "CrmCallReview"("orgId");

-- CreateIndex
CREATE INDEX "CrmCallReview_recordingId_idx" ON "CrmCallReview"("recordingId");

-- CreateIndex
CREATE INDEX "CrmCallReview_reviewerId_idx" ON "CrmCallReview"("reviewerId");

-- CreateIndex
CREATE INDEX "CrmCallRecordingAuditLog_orgId_idx" ON "CrmCallRecordingAuditLog"("orgId");

-- CreateIndex
CREATE INDEX "CrmCallRecordingAuditLog_recordingId_idx" ON "CrmCallRecordingAuditLog"("recordingId");

-- CreateIndex
CREATE INDEX "CrmCallRecordingAuditLog_userId_idx" ON "CrmCallRecordingAuditLog"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "GoogleWorkspaceConnection_userId_key" ON "GoogleWorkspaceConnection"("userId");

-- CreateIndex
CREATE INDEX "GoogleWorkspaceConnection_orgId_idx" ON "GoogleWorkspaceConnection"("orgId");

-- CreateIndex
CREATE UNIQUE INDEX "GoogleWorkspaceSetting_orgId_key" ON "GoogleWorkspaceSetting"("orgId");

-- CreateIndex
CREATE INDEX "GoogleWorkspaceSetting_orgId_idx" ON "GoogleWorkspaceSetting"("orgId");

-- CreateIndex
CREATE INDEX "CommunicationAuditEvent_orgId_idx" ON "CommunicationAuditEvent"("orgId");

-- CreateIndex
CREATE INDEX "CommunicationAuditEvent_userId_idx" ON "CommunicationAuditEvent"("userId");

-- CreateIndex
CREATE INDEX "ChaTeamGroup_orgId_idx" ON "ChaTeamGroup"("orgId");

-- CreateIndex
CREATE UNIQUE INDEX "ChaTeamGroup_orgId_name_key" ON "ChaTeamGroup"("orgId", "name");

-- CreateIndex
CREATE INDEX "ChaDoExtension_jobId_createdAt_idx" ON "ChaDoExtension"("jobId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitSetting_orgId_key" ON "RecruitSetting"("orgId");

-- CreateIndex
CREATE INDEX "RecruitSetting_orgId_idx" ON "RecruitSetting"("orgId");

-- CreateIndex
CREATE INDEX "RecruitJobOpening_orgId_status_idx" ON "RecruitJobOpening"("orgId", "status");

-- CreateIndex
CREATE INDEX "RecruitJobOpening_orgId_departmentId_idx" ON "RecruitJobOpening"("orgId", "departmentId");

-- CreateIndex
CREATE INDEX "RecruitJobOpening_orgId_branchId_idx" ON "RecruitJobOpening"("orgId", "branchId");

-- CreateIndex
CREATE INDEX "RecruitJobOpening_orgId_closingDate_idx" ON "RecruitJobOpening"("orgId", "closingDate");

-- CreateIndex
CREATE INDEX "RecruitJobVersion_jobOpeningId_version_idx" ON "RecruitJobVersion"("jobOpeningId", "version");

-- CreateIndex
CREATE INDEX "RecruitCandidate_orgId_email_idx" ON "RecruitCandidate"("orgId", "email");

-- CreateIndex
CREATE INDEX "RecruitCandidate_orgId_phone_idx" ON "RecruitCandidate"("orgId", "phone");

-- CreateIndex
CREATE INDEX "RecruitCandidate_orgId_resumeHash_idx" ON "RecruitCandidate"("orgId", "resumeHash");

-- CreateIndex
CREATE INDEX "RecruitCandidate_orgId_deletedAt_idx" ON "RecruitCandidate"("orgId", "deletedAt");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitCandidate_orgId_candidateNumber_key" ON "RecruitCandidate"("orgId", "candidateNumber");

-- CreateIndex
CREATE INDEX "RecruitCandidateConsent_candidateId_idx" ON "RecruitCandidateConsent"("candidateId");

-- CreateIndex
CREATE INDEX "RecruitCandidateResume_candidateId_isActive_idx" ON "RecruitCandidateResume"("candidateId", "isActive");

-- CreateIndex
CREATE INDEX "RecruitCandidateResume_resumeHash_idx" ON "RecruitCandidateResume"("resumeHash");

-- CreateIndex
CREATE INDEX "RecruitCandidateEducation_candidateId_idx" ON "RecruitCandidateEducation"("candidateId");

-- CreateIndex
CREATE INDEX "RecruitCandidateExperience_candidateId_idx" ON "RecruitCandidateExperience"("candidateId");

-- CreateIndex
CREATE INDEX "RecruitCandidateSkill_candidateId_idx" ON "RecruitCandidateSkill"("candidateId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitCandidateSkill_candidateId_skill_key" ON "RecruitCandidateSkill"("candidateId", "skill");

-- CreateIndex
CREATE INDEX "RecruitApplication_orgId_stage_idx" ON "RecruitApplication"("orgId", "stage");

-- CreateIndex
CREATE INDEX "RecruitApplication_orgId_jobOpeningId_idx" ON "RecruitApplication"("orgId", "jobOpeningId");

-- CreateIndex
CREATE INDEX "RecruitApplication_orgId_candidateId_idx" ON "RecruitApplication"("orgId", "candidateId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitApplication_orgId_applicationNumber_key" ON "RecruitApplication"("orgId", "applicationNumber");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitApplication_jobOpeningId_candidateId_key" ON "RecruitApplication"("jobOpeningId", "candidateId");

-- CreateIndex
CREATE INDEX "RecruitApplicationStageHistory_applicationId_movedAt_idx" ON "RecruitApplicationStageHistory"("applicationId", "movedAt");

-- CreateIndex
CREATE INDEX "RecruitScreeningAnswer_applicationId_idx" ON "RecruitScreeningAnswer"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitScreeningAnswer_applicationId_questionId_key" ON "RecruitScreeningAnswer"("applicationId", "questionId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitScreeningRun_idempotencyKey_key" ON "RecruitScreeningRun"("idempotencyKey");

-- CreateIndex
CREATE INDEX "RecruitScreeningRun_applicationId_idx" ON "RecruitScreeningRun"("applicationId");

-- CreateIndex
CREATE INDEX "RecruitScreeningRun_orgId_idx" ON "RecruitScreeningRun"("orgId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitScreeningResult_runId_key" ON "RecruitScreeningResult"("runId");

-- CreateIndex
CREATE INDEX "RecruitScreeningResult_runId_idx" ON "RecruitScreeningResult"("runId");

-- CreateIndex
CREATE INDEX "RecruitScreeningResult_resumeVersionId_idx" ON "RecruitScreeningResult"("resumeVersionId");

-- CreateIndex
CREATE INDEX "RecruitInterview_applicationId_idx" ON "RecruitInterview"("applicationId");

-- CreateIndex
CREATE INDEX "RecruitInterview_orgId_scheduledAt_idx" ON "RecruitInterview"("orgId", "scheduledAt");

-- CreateIndex
CREATE INDEX "RecruitInterviewPanel_interviewId_idx" ON "RecruitInterviewPanel"("interviewId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitInterviewPanel_interviewId_userId_key" ON "RecruitInterviewPanel"("interviewId", "userId");

-- CreateIndex
CREATE INDEX "RecruitInterviewFeedback_interviewId_idx" ON "RecruitInterviewFeedback"("interviewId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitInterviewFeedback_interviewId_userId_key" ON "RecruitInterviewFeedback"("interviewId", "userId");

-- CreateIndex
CREATE INDEX "RecruitAssessment_applicationId_idx" ON "RecruitAssessment"("applicationId");

-- CreateIndex
CREATE INDEX "RecruitAssessment_orgId_idx" ON "RecruitAssessment"("orgId");

-- CreateIndex
CREATE INDEX "RecruitAssessmentAttempt_assessmentId_idx" ON "RecruitAssessmentAttempt"("assessmentId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitOffer_candidateAccessToken_key" ON "RecruitOffer"("candidateAccessToken");

-- CreateIndex
CREATE INDEX "RecruitOffer_applicationId_idx" ON "RecruitOffer"("applicationId");

-- CreateIndex
CREATE INDEX "RecruitOffer_candidateAccessToken_idx" ON "RecruitOffer"("candidateAccessToken");

-- CreateIndex
CREATE INDEX "RecruitOffer_orgId_idx" ON "RecruitOffer"("orgId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitOffer_orgId_offerNumber_key" ON "RecruitOffer"("orgId", "offerNumber");

-- CreateIndex
CREATE INDEX "RecruitOfferApproval_offerId_idx" ON "RecruitOfferApproval"("offerId");

-- CreateIndex
CREATE INDEX "RecruitNote_orgId_candidateId_idx" ON "RecruitNote"("orgId", "candidateId");

-- CreateIndex
CREATE INDEX "RecruitNote_orgId_applicationId_idx" ON "RecruitNote"("orgId", "applicationId");

-- CreateIndex
CREATE INDEX "RecruitTag_orgId_candidateId_idx" ON "RecruitTag"("orgId", "candidateId");

-- CreateIndex
CREATE INDEX "RecruitAttachment_orgId_candidateId_idx" ON "RecruitAttachment"("orgId", "candidateId");

-- CreateIndex
CREATE INDEX "RecruitAttachment_orgId_applicationId_idx" ON "RecruitAttachment"("orgId", "applicationId");

-- CreateIndex
CREATE INDEX "RecruitAutomationRun_orgId_createdAt_idx" ON "RecruitAutomationRun"("orgId", "createdAt");

-- CreateIndex
CREATE INDEX "RecruitAutomationRunItem_runId_idx" ON "RecruitAutomationRunItem"("runId");

-- CreateIndex
CREATE INDEX "RecruitAutomationRunItem_applicationId_idx" ON "RecruitAutomationRunItem"("applicationId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitHandoffPackage_applicationId_key" ON "RecruitHandoffPackage"("applicationId");

-- CreateIndex
CREATE INDEX "RecruitHandoffPackage_orgId_idx" ON "RecruitHandoffPackage"("orgId");

-- CreateIndex
CREATE INDEX "RecruitAuditEvent_orgId_createdAt_idx" ON "RecruitAuditEvent"("orgId", "createdAt");

-- CreateIndex
CREATE INDEX "RecruitAuditEvent_orgId_entityType_entityId_idx" ON "RecruitAuditEvent"("orgId", "entityType", "entityId");

-- CreateIndex
CREATE INDEX "RecruitAuditEvent_actorId_idx" ON "RecruitAuditEvent"("actorId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitJobSeekerProfile_ownerId_key" ON "RecruitJobSeekerProfile"("ownerId");

-- CreateIndex
CREATE INDEX "RecruitJobSeekerProfile_ownerId_idx" ON "RecruitJobSeekerProfile"("ownerId");

-- CreateIndex
CREATE INDEX "RecruitJobSearchProfile_profileId_idx" ON "RecruitJobSearchProfile"("profileId");

-- CreateIndex
CREATE INDEX "RecruitJobListing_ownerId_idx" ON "RecruitJobListing"("ownerId");

-- CreateIndex
CREATE INDEX "RecruitJobListing_ownerId_isDismissed_isExpired_idx" ON "RecruitJobListing"("ownerId", "isDismissed", "isExpired");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitJobListing_ownerId_source_externalId_key" ON "RecruitJobListing"("ownerId", "source", "externalId");

-- CreateIndex
CREATE INDEX "RecruitSavedJob_profileId_idx" ON "RecruitSavedJob"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitSavedJob_profileId_listingId_key" ON "RecruitSavedJob"("profileId", "listingId");

-- CreateIndex
CREATE INDEX "RecruitJobMatch_ownerId_idx" ON "RecruitJobMatch"("ownerId");

-- CreateIndex
CREATE INDEX "RecruitJobMatch_searchProfileId_idx" ON "RecruitJobMatch"("searchProfileId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitJobMatch_searchProfileId_listingId_key" ON "RecruitJobMatch"("searchProfileId", "listingId");

-- CreateIndex
CREATE INDEX "RecruitJobSeekerResume_profileId_isBase_idx" ON "RecruitJobSeekerResume"("profileId", "isBase");

-- CreateIndex
CREATE INDEX "RecruitJobSeekerResume_ownerId_idx" ON "RecruitJobSeekerResume"("ownerId");

-- CreateIndex
CREATE INDEX "RecruitTailoredResume_ownerId_idx" ON "RecruitTailoredResume"("ownerId");

-- CreateIndex
CREATE INDEX "RecruitTailoredResume_baseResumeId_idx" ON "RecruitTailoredResume"("baseResumeId");

-- CreateIndex
CREATE INDEX "RecruitCoverLetter_ownerId_idx" ON "RecruitCoverLetter"("ownerId");

-- CreateIndex
CREATE INDEX "RecruitCoverLetter_baseResumeId_idx" ON "RecruitCoverLetter"("baseResumeId");

-- CreateIndex
CREATE INDEX "RecruitJobSeekerApplication_ownerId_privateStatus_idx" ON "RecruitJobSeekerApplication"("ownerId", "privateStatus");

-- CreateIndex
CREATE INDEX "RecruitJobSeekerApplication_profileId_idx" ON "RecruitJobSeekerApplication"("profileId");

-- CreateIndex
CREATE INDEX "RecruitJobAlert_ownerId_isActive_idx" ON "RecruitJobAlert"("ownerId", "isActive");

-- CreateIndex
CREATE INDEX "RecruitJobAlert_frequency_lastDeliveredAt_idx" ON "RecruitJobAlert"("frequency", "lastDeliveredAt");

-- CreateIndex
CREATE INDEX "RecruitCareerConversation_ownerId_idx" ON "RecruitCareerConversation"("ownerId");

-- CreateIndex
CREATE INDEX "RecruitCareerConversation_profileId_idx" ON "RecruitCareerConversation"("profileId");

-- CreateIndex
CREATE INDEX "RecruitCareerMessage_conversationId_createdAt_idx" ON "RecruitCareerMessage"("conversationId", "createdAt");

-- CreateIndex
CREATE INDEX "RecruitInterviewPrep_ownerId_idx" ON "RecruitInterviewPrep"("ownerId");

-- CreateIndex
CREATE UNIQUE INDEX "RecruitPrivateShare_token_key" ON "RecruitPrivateShare"("token");

-- CreateIndex
CREATE INDEX "RecruitPrivateShare_ownerId_idx" ON "RecruitPrivateShare"("ownerId");

-- CreateIndex
CREATE INDEX "RecruitPrivateShare_token_idx" ON "RecruitPrivateShare"("token");

-- CreateIndex
CREATE INDEX "RecruitPrivateShare_expiresAt_idx" ON "RecruitPrivateShare"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "GoogleChatUserLink_userId_key" ON "GoogleChatUserLink"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "GoogleChatUserLink_googleUserId_key" ON "GoogleChatUserLink"("googleUserId");

-- CreateIndex
CREATE INDEX "GoogleChatUserLink_orgId_idx" ON "GoogleChatUserLink"("orgId");

-- CreateIndex
CREATE INDEX "GoogleChatUserLink_googleEmail_idx" ON "GoogleChatUserLink"("googleEmail");

-- CreateIndex
CREATE INDEX "GoogleChatUserLink_linkStatus_idx" ON "GoogleChatUserLink"("linkStatus");

-- CreateIndex
CREATE UNIQUE INDEX "GoogleChatSpace_spaceResourceName_key" ON "GoogleChatSpace"("spaceResourceName");

-- CreateIndex
CREATE INDEX "GoogleChatSpace_orgId_idx" ON "GoogleChatSpace"("orgId");

-- CreateIndex
CREATE INDEX "GoogleChatSpace_linkedRecordType_linkedRecordId_idx" ON "GoogleChatSpace"("linkedRecordType", "linkedRecordId");

-- CreateIndex
CREATE INDEX "GoogleChatSpace_linkStatus_idx" ON "GoogleChatSpace"("linkStatus");

-- CreateIndex
CREATE INDEX "GoogleChatSubscription_orgId_idx" ON "GoogleChatSubscription"("orgId");

-- CreateIndex
CREATE INDEX "GoogleChatSubscription_userId_idx" ON "GoogleChatSubscription"("userId");

-- CreateIndex
CREATE INDEX "GoogleChatSubscription_spaceId_idx" ON "GoogleChatSubscription"("spaceId");

-- CreateIndex
CREATE INDEX "GoogleChatSubscription_enabled_idx" ON "GoogleChatSubscription"("enabled");

-- CreateIndex
CREATE UNIQUE INDEX "GoogleChatDelivery_idempotencyKey_key" ON "GoogleChatDelivery"("idempotencyKey");

-- CreateIndex
CREATE INDEX "GoogleChatDelivery_status_nextAttemptAt_idx" ON "GoogleChatDelivery"("status", "nextAttemptAt");

-- CreateIndex
CREATE INDEX "GoogleChatDelivery_orgId_idx" ON "GoogleChatDelivery"("orgId");

-- CreateIndex
CREATE INDEX "GoogleChatDelivery_targetUserId_idx" ON "GoogleChatDelivery"("targetUserId");

-- CreateIndex
CREATE INDEX "GoogleChatDelivery_notificationId_idx" ON "GoogleChatDelivery"("notificationId");

-- CreateIndex
CREATE UNIQUE INDEX "GoogleChatInteractionEvent_googleEventId_key" ON "GoogleChatInteractionEvent"("googleEventId");

-- CreateIndex
CREATE INDEX "GoogleChatInteractionEvent_processedAt_idx" ON "GoogleChatInteractionEvent"("processedAt");

-- CreateIndex
CREATE UNIQUE INDEX "GoogleChatLinkToken_token_key" ON "GoogleChatLinkToken"("token");

-- CreateIndex
CREATE INDEX "GoogleChatLinkToken_expiresAt_idx" ON "GoogleChatLinkToken"("expiresAt");

-- CreateIndex
CREATE INDEX "GoogleChatLinkToken_googleUserId_idx" ON "GoogleChatLinkToken"("googleUserId");

-- CreateIndex
CREATE INDEX "MobileDevice_orgId_idx" ON "MobileDevice"("orgId");

-- CreateIndex
CREATE INDEX "MobileDevice_userId_isActive_idx" ON "MobileDevice"("userId", "isActive");

-- CreateIndex
CREATE UNIQUE INDEX "MobileDevice_userId_deviceId_key" ON "MobileDevice"("userId", "deviceId");

-- CreateIndex
CREATE UNIQUE INDEX "EmployeeFaceEnrollment_userId_key" ON "EmployeeFaceEnrollment"("userId");

-- CreateIndex
CREATE INDEX "EmployeeFaceEnrollment_orgId_idx" ON "EmployeeFaceEnrollment"("orgId");

-- CreateIndex
CREATE INDEX "AttendanceSession_orgId_date_idx" ON "AttendanceSession"("orgId", "date");

-- CreateIndex
CREATE INDEX "AttendanceSession_userId_date_idx" ON "AttendanceSession"("userId", "date");

-- CreateIndex
CREATE INDEX "AttendanceSession_userId_status_idx" ON "AttendanceSession"("userId", "status");

-- CreateIndex
CREATE INDEX "LocationTrackingSession_orgId_status_idx" ON "LocationTrackingSession"("orgId", "status");

-- CreateIndex
CREATE INDEX "LocationTrackingSession_userId_status_idx" ON "LocationTrackingSession"("userId", "status");

-- CreateIndex
CREATE INDEX "LocationPoint_trackingSessionId_timestamp_idx" ON "LocationPoint"("trackingSessionId", "timestamp");

-- CreateIndex
CREATE INDEX "LocationPoint_timestamp_idx" ON "LocationPoint"("timestamp");

-- CreateIndex
CREATE INDEX "TrackingAlert_orgId_alertType_idx" ON "TrackingAlert"("orgId", "alertType");

-- CreateIndex
CREATE INDEX "TrackingAlert_userId_resolvedAt_idx" ON "TrackingAlert"("userId", "resolvedAt");

-- CreateIndex
CREATE INDEX "FuelReimbursementPolicy_orgId_isActive_idx" ON "FuelReimbursementPolicy"("orgId", "isActive");

-- CreateIndex
CREATE INDEX "FuelReimbursementClaim_orgId_status_idx" ON "FuelReimbursementClaim"("orgId", "status");

-- CreateIndex
CREATE INDEX "FuelReimbursementClaim_userId_status_idx" ON "FuelReimbursementClaim"("userId", "status");

-- CreateIndex
CREATE INDEX "UserAgreementVersion_orgId_isActive_idx" ON "UserAgreementVersion"("orgId", "isActive");

-- CreateIndex
CREATE UNIQUE INDEX "UserAgreementVersion_orgId_version_key" ON "UserAgreementVersion"("orgId", "version");

-- CreateIndex
CREATE INDEX "UserAgreementAcceptance_orgId_idx" ON "UserAgreementAcceptance"("orgId");

-- CreateIndex
CREATE UNIQUE INDEX "UserAgreementAcceptance_userId_agreementVersionId_key" ON "UserAgreementAcceptance"("userId", "agreementVersionId");

-- CreateIndex
CREATE INDEX "AppraisalExtensionRequest_requesterId_idx" ON "AppraisalExtensionRequest"("requesterId");

-- CreateIndex
CREATE INDEX "AppraisalExtensionRequest_appraisalId_idx" ON "AppraisalExtensionRequest"("appraisalId");

-- CreateIndex
CREATE INDEX "ChaCustomerAdvance_status_idx" ON "ChaCustomerAdvance"("status");

-- CreateIndex
CREATE INDEX "ChaJob_assignedManagerId_idx" ON "ChaJob"("assignedManagerId");

-- CreateIndex
CREATE INDEX "CrmLead_orgId_isConverted_status_idx" ON "CrmLead"("orgId", "isConverted", "status");

-- CreateIndex
CREATE INDEX "GeneralLedgerEntry_orgId_isCancelled_idx" ON "GeneralLedgerEntry"("orgId", "isCancelled");

-- CreateIndex
CREATE INDEX "GeneralLedgerEntry_accountId_isCancelled_idx" ON "GeneralLedgerEntry"("accountId", "isCancelled");

-- CreateIndex
CREATE UNIQUE INDEX "HRLetterRequest_letterNumber_key" ON "HRLetterRequest"("letterNumber");

-- CreateIndex
CREATE INDEX "OnDutyRequest_orgId_status_idx" ON "OnDutyRequest"("orgId", "status");

-- CreateIndex
CREATE INDEX "OnDutyRequest_userId_status_idx" ON "OnDutyRequest"("userId", "status");

-- CreateIndex
CREATE INDEX "OtRecord_approvalStatus_idx" ON "OtRecord"("approvalStatus");

-- CreateIndex
CREATE UNIQUE INDEX "User_employeeNumber_key" ON "User"("employeeNumber");

-- CreateIndex
CREATE INDEX "UserSession_expiresAt_idx" ON "UserSession"("expiresAt");

-- AddForeignKey
ALTER TABLE "CrmCallAttempt" ADD CONSTRAINT "CrmCallAttempt_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "CrmLead"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CrmCallAttempt" ADD CONSTRAINT "CrmCallAttempt_salespersonId_fkey" FOREIGN KEY ("salespersonId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CrmCallRecording" ADD CONSTRAINT "CrmCallRecording_callAttemptId_fkey" FOREIGN KEY ("callAttemptId") REFERENCES "CrmCallAttempt"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CrmCallTranscript" ADD CONSTRAINT "CrmCallTranscript_recordingId_fkey" FOREIGN KEY ("recordingId") REFERENCES "CrmCallRecording"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CrmCallReview" ADD CONSTRAINT "CrmCallReview_recordingId_fkey" FOREIGN KEY ("recordingId") REFERENCES "CrmCallRecording"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CrmCallReview" ADD CONSTRAINT "CrmCallReview_reviewerId_fkey" FOREIGN KEY ("reviewerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CrmCallRecordingAuditLog" ADD CONSTRAINT "CrmCallRecordingAuditLog_recordingId_fkey" FOREIGN KEY ("recordingId") REFERENCES "CrmCallRecording"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CrmCallRecordingAuditLog" ADD CONSTRAINT "CrmCallRecordingAuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GoogleWorkspaceConnection" ADD CONSTRAINT "GoogleWorkspaceConnection_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GoogleWorkspaceConnection" ADD CONSTRAINT "GoogleWorkspaceConnection_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GoogleWorkspaceSetting" ADD CONSTRAINT "GoogleWorkspaceSetting_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CommunicationAuditEvent" ADD CONSTRAINT "CommunicationAuditEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CommunicationAuditEvent" ADD CONSTRAINT "CommunicationAuditEvent_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChaTeamGroup" ADD CONSTRAINT "ChaTeamGroup_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChaJob" ADD CONSTRAINT "ChaJob_assignedManagerId_fkey" FOREIGN KEY ("assignedManagerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChaDoExtension" ADD CONSTRAINT "ChaDoExtension_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "ChaJob"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitSetting" ADD CONSTRAINT "RecruitSetting_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobOpening" ADD CONSTRAINT "RecruitJobOpening_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobVersion" ADD CONSTRAINT "RecruitJobVersion_jobOpeningId_fkey" FOREIGN KEY ("jobOpeningId") REFERENCES "RecruitJobOpening"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCandidate" ADD CONSTRAINT "RecruitCandidate_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCandidateConsent" ADD CONSTRAINT "RecruitCandidateConsent_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "RecruitCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCandidateResume" ADD CONSTRAINT "RecruitCandidateResume_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "RecruitCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCandidateEducation" ADD CONSTRAINT "RecruitCandidateEducation_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "RecruitCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCandidateExperience" ADD CONSTRAINT "RecruitCandidateExperience_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "RecruitCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCandidateSkill" ADD CONSTRAINT "RecruitCandidateSkill_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "RecruitCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitApplication" ADD CONSTRAINT "RecruitApplication_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitApplication" ADD CONSTRAINT "RecruitApplication_jobOpeningId_fkey" FOREIGN KEY ("jobOpeningId") REFERENCES "RecruitJobOpening"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitApplication" ADD CONSTRAINT "RecruitApplication_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "RecruitCandidate"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitApplicationStageHistory" ADD CONSTRAINT "RecruitApplicationStageHistory_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitScreeningAnswer" ADD CONSTRAINT "RecruitScreeningAnswer_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitScreeningRun" ADD CONSTRAINT "RecruitScreeningRun_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitScreeningResult" ADD CONSTRAINT "RecruitScreeningResult_runId_fkey" FOREIGN KEY ("runId") REFERENCES "RecruitScreeningRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitScreeningResult" ADD CONSTRAINT "RecruitScreeningResult_resumeVersionId_fkey" FOREIGN KEY ("resumeVersionId") REFERENCES "RecruitCandidateResume"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitInterview" ADD CONSTRAINT "RecruitInterview_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitInterviewPanel" ADD CONSTRAINT "RecruitInterviewPanel_interviewId_fkey" FOREIGN KEY ("interviewId") REFERENCES "RecruitInterview"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitInterviewFeedback" ADD CONSTRAINT "RecruitInterviewFeedback_interviewId_fkey" FOREIGN KEY ("interviewId") REFERENCES "RecruitInterview"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitAssessment" ADD CONSTRAINT "RecruitAssessment_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitAssessmentAttempt" ADD CONSTRAINT "RecruitAssessmentAttempt_assessmentId_fkey" FOREIGN KEY ("assessmentId") REFERENCES "RecruitAssessment"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitOffer" ADD CONSTRAINT "RecruitOffer_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitOfferApproval" ADD CONSTRAINT "RecruitOfferApproval_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "RecruitOffer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitNote" ADD CONSTRAINT "RecruitNote_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "RecruitCandidate"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitNote" ADD CONSTRAINT "RecruitNote_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitApplication"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitTag" ADD CONSTRAINT "RecruitTag_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "RecruitCandidate"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitAutomationRun" ADD CONSTRAINT "RecruitAutomationRun_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitAutomationRunItem" ADD CONSTRAINT "RecruitAutomationRunItem_runId_fkey" FOREIGN KEY ("runId") REFERENCES "RecruitAutomationRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitAuditEvent" ADD CONSTRAINT "RecruitAuditEvent_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobSeekerProfile" ADD CONSTRAINT "RecruitJobSeekerProfile_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobSearchProfile" ADD CONSTRAINT "RecruitJobSearchProfile_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "RecruitJobSeekerProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobListing" ADD CONSTRAINT "RecruitJobListing_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitSavedJob" ADD CONSTRAINT "RecruitSavedJob_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "RecruitJobSeekerProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitSavedJob" ADD CONSTRAINT "RecruitSavedJob_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "RecruitJobListing"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobMatch" ADD CONSTRAINT "RecruitJobMatch_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobMatch" ADD CONSTRAINT "RecruitJobMatch_searchProfileId_fkey" FOREIGN KEY ("searchProfileId") REFERENCES "RecruitJobSearchProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobMatch" ADD CONSTRAINT "RecruitJobMatch_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "RecruitJobListing"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobSeekerResume" ADD CONSTRAINT "RecruitJobSeekerResume_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobSeekerResume" ADD CONSTRAINT "RecruitJobSeekerResume_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "RecruitJobSeekerProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitTailoredResume" ADD CONSTRAINT "RecruitTailoredResume_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitTailoredResume" ADD CONSTRAINT "RecruitTailoredResume_baseResumeId_fkey" FOREIGN KEY ("baseResumeId") REFERENCES "RecruitJobSeekerResume"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCoverLetter" ADD CONSTRAINT "RecruitCoverLetter_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCoverLetter" ADD CONSTRAINT "RecruitCoverLetter_baseResumeId_fkey" FOREIGN KEY ("baseResumeId") REFERENCES "RecruitJobSeekerResume"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobSeekerApplication" ADD CONSTRAINT "RecruitJobSeekerApplication_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobSeekerApplication" ADD CONSTRAINT "RecruitJobSeekerApplication_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "RecruitJobSeekerProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobAlert" ADD CONSTRAINT "RecruitJobAlert_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobAlert" ADD CONSTRAINT "RecruitJobAlert_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "RecruitJobSeekerProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitJobAlert" ADD CONSTRAINT "RecruitJobAlert_searchProfileId_fkey" FOREIGN KEY ("searchProfileId") REFERENCES "RecruitJobSearchProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCareerConversation" ADD CONSTRAINT "RecruitCareerConversation_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCareerConversation" ADD CONSTRAINT "RecruitCareerConversation_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "RecruitJobSeekerProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitCareerMessage" ADD CONSTRAINT "RecruitCareerMessage_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "RecruitCareerConversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitInterviewPrep" ADD CONSTRAINT "RecruitInterviewPrep_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecruitPrivateShare" ADD CONSTRAINT "RecruitPrivateShare_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GoogleChatUserLink" ADD CONSTRAINT "GoogleChatUserLink_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GoogleChatSpace" ADD CONSTRAINT "GoogleChatSpace_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GoogleChatSubscription" ADD CONSTRAINT "GoogleChatSubscription_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GoogleChatSubscription" ADD CONSTRAINT "GoogleChatSubscription_spaceId_fkey" FOREIGN KEY ("spaceId") REFERENCES "GoogleChatSpace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GoogleChatDelivery" ADD CONSTRAINT "GoogleChatDelivery_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Organisation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GoogleChatDelivery" ADD CONSTRAINT "GoogleChatDelivery_targetSpaceId_fkey" FOREIGN KEY ("targetSpaceId") REFERENCES "GoogleChatSpace"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MobileDevice" ADD CONSTRAINT "MobileDevice_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmployeeFaceEnrollment" ADD CONSTRAINT "EmployeeFaceEnrollment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AttendanceSession" ADD CONSTRAINT "AttendanceSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LocationTrackingSession" ADD CONSTRAINT "LocationTrackingSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LocationTrackingSession" ADD CONSTRAINT "LocationTrackingSession_attendanceSessionId_fkey" FOREIGN KEY ("attendanceSessionId") REFERENCES "AttendanceSession"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LocationTrackingSession" ADD CONSTRAINT "LocationTrackingSession_onDutyRequestId_fkey" FOREIGN KEY ("onDutyRequestId") REFERENCES "OnDutyRequest"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LocationPoint" ADD CONSTRAINT "LocationPoint_trackingSessionId_fkey" FOREIGN KEY ("trackingSessionId") REFERENCES "LocationTrackingSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TrackingAlert" ADD CONSTRAINT "TrackingAlert_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TrackingAlert" ADD CONSTRAINT "TrackingAlert_trackingSessionId_fkey" FOREIGN KEY ("trackingSessionId") REFERENCES "LocationTrackingSession"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FuelReimbursementClaim" ADD CONSTRAINT "FuelReimbursementClaim_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FuelReimbursementClaim" ADD CONSTRAINT "FuelReimbursementClaim_onDutyRequestId_fkey" FOREIGN KEY ("onDutyRequestId") REFERENCES "OnDutyRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserAgreementAcceptance" ADD CONSTRAINT "UserAgreementAcceptance_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserAgreementAcceptance" ADD CONSTRAINT "UserAgreementAcceptance_agreementVersionId_fkey" FOREIGN KEY ("agreementVersionId") REFERENCES "UserAgreementVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- RenameIndex
ALTER INDEX "TodoTask_userId_status_reminderEnabled_alertAt_alertTriggeredAt" RENAME TO "TodoTask_userId_status_reminderEnabled_alertAt_alertTrigger_idx";
