import type { ItemListItem } from "./types";

export const MOCK_ITEMS: ItemListItem[] = [
  {
    id: "ITEM-001",
    name: "A.A.I. CHARGES EXPENSES",
    sku: "",
    purchaseDescription: "",
    purchaseRate: 0,
    description: "",
    rate: 5655,
    hsnSac: "",
    usageUnit: "",
    type: "Service",
    taxPreference: "Taxable",
    status: "Active",
  },
  {
    id: "ITEM-002",
    name: "AAICLAS CHARGES - Taxable",
    sku: "",
    purchaseDescription: "",
    purchaseRate: 1,
    description: "",
    rate: 1,
    hsnSac: "996719",
    usageUnit: "",
    type: "Service",
    taxPreference: "Taxable",
    status: "Active",
  },
  {
    id: "ITEM-003",
    name: "AD Code Registration Charges",
    sku: "",
    purchaseDescription: "",
    purchaseRate: 1,
    description: "",
    rate: 1,
    hsnSac: "996712",
    usageUnit: "",
    type: "Service",
    taxPreference: "Taxable",
    status: "Active",
  },
  {
    id: "ITEM-004",
    name: "ADC NOC Charges",
    sku: "",
    purchaseDescription: "",
    purchaseRate: 1,
    description: "",
    rate: 1,
    hsnSac: "996712",
    usageUnit: "",
    type: "Service",
    taxPreference: "Taxable",
    status: "Active",
  },
  {
    id: "ITEM-005",
    name: "Additional Separation (Pallet)",
    sku: "",
    purchaseDescription: "",
    purchaseRate: 1,
    description: "",
    rate: 1,
    hsnSac: "996712",
    usageUnit: "",
    type: "Service",
    taxPreference: "Taxable",
    status: "Active",
  },
  {
    id: "ITEM-006",
    name: "Admin Charges",
    sku: "",
    purchaseDescription: "",
    purchaseRate: 0,
    description: "",
    rate: 25,
    hsnSac: "996712",
    usageUnit: "",
    type: "Service",
    taxPreference: "Taxable",
    status: "Active",
  },
  {
    id: "ITEM-007",
    name: "AEPC RCMC",
    sku: "",
    purchaseDescription: "",
    purchaseRate: 1,
    description: "",
    rate: 1,
    hsnSac: "996712",
    usageUnit: "",
    type: "Service",
    taxPreference: "Non-Taxable",
    status: "Active",
  },
  {
    id: "ITEM-008",
    name: "Agency Charges",
    sku: "AGENCY-001",
    purchaseDescription: "Agency handling charge",
    purchaseRate: 500,
    description: "Agency handling charge",
    rate: 1500,
    hsnSac: "996712",
    usageUnit: "Shipment",
    type: "Service",
    taxPreference: "Taxable",
    status: "Active",
  },
  {
    id: "ITEM-009",
    name: "Customs Clearance Charges",
    sku: "CUS-CLR-001",
    purchaseDescription: "Customs clearance service",
    purchaseRate: 1000,
    description: "Customs clearance service",
    rate: 3500,
    hsnSac: "996712",
    usageUnit: "Shipment",
    type: "Service",
    taxPreference: "Taxable",
    status: "Active",
  },
  {
    id: "ITEM-010",
    name: "Freight Forwarding Charges",
    sku: "FRT-FWD-001",
    purchaseDescription: "Freight forwarding service",
    purchaseRate: 2500,
    description: "Freight forwarding service",
    rate: 7500,
    hsnSac: "996719",
    usageUnit: "Container",
    type: "Service",
    taxPreference: "Taxable",
    status: "Active",
  },
];
