import { z } from "zod";

const requiredString = (label: string) => z.string().trim().min(1, `${label} is required.`);
const optionalString = z.string();
const optionalBoolean = z.boolean();

export const importMainDetailsSchema = z.object({
  jobNo: optionalString,
  jobDate: optionalString,
  beType: requiredString("BE Type"),
  transportMode: requiredString("Transport Mode"),
  filingType: requiredString("Filing Type"),
  customsHouse: requiredString("Customs House"),
  customsHouseCode: requiredString("Customs House Code"),
  warehouseCode: optionalString,
  warehouseCustomsSiteId: optionalString,
  numberOfPackages: optionalString,
  packageCode: optionalString,
  grossWeight: optionalString,
  uom: optionalString,
  beNo: optionalString,
  beDate: optionalString,
  examinationDate: optionalString,
  oocDate: optionalString,
  dutyPaidDate: optionalString,
  deliveredDate: optionalString,
  icegateId: requiredString("ICEGATE ID"),
  chaPanNo: optionalString,
  atpName: optionalString,
  atpPanNo: optionalString,
  standardIec: requiredString("Standard IEC"),
  importerName: requiredString("Importer Name"),
  iecNo: requiredString("IEC No"),
  branchSerialNo: requiredString("Branch Serial No"),
  importerCategory: requiredString("Importer Category"),
  importerType: requiredString("Importer Type"),
  importerClass: requiredString("Importer Class"),
  address: optionalString,
  city: optionalString,
  state: optionalString,
  pinCode: optionalString,
  adCode: requiredString("AD Code"),
  stateOfOrigin: requiredString("State of Origin"),
  gstnType: requiredString("GSTN Type"),
  taxRegistrationNo: optionalString,
  firstCheck: optionalBoolean,
  greenChannel: optionalBoolean,
  kacchaBe: optionalBoolean,
  provisionalAssessment: optionalBoolean,
  highSeaSale: optionalBoolean,
  exBond: optionalBoolean,
  ucrType: optionalString,
  ucrNo: optionalString,
  paymentMethod: requiredString("Payment Method"),
  bondDetails: optionalString,
  certificateDetails: optionalString,
  portOfShipment: requiredString("Port of Shipment"),
  portOfShipmentCode: optionalString,
  countryOfShipment: requiredString("Country of Shipment"),
  countryOfShipmentCode: optionalString,
  portOfOrigin: requiredString("Port of Origin"),
  portOfOriginCode: optionalString,
  countryOfOrigin: requiredString("Country of Origin"),
  countryOfOriginCode: optionalString,
  otherDetails: optionalString,
});

export const importIgmRecordSchema = z.object({
  igmNo: requiredString("IGM No"),
  igmDate: requiredString("IGM Date"),
  inwardDate: optionalString,
  gatewayPort: optionalString,
  gatewayMode: optionalString,
  mblNo: requiredString("MBL No"),
  noMbl: optionalBoolean,
  mblDate: requiredString("MBL Date"),
  numberOfPackages: requiredString("Number of Packages"),
  packageCode: requiredString("Package Code"),
  twentyFtCount: optionalString,
  fortyFtCount: optionalString,
  hblNo: optionalString,
  hblDate: optionalString,
  grossWeight: requiredString("Gross Weight"),
  netWeight: optionalString,
  uom: requiredString("UOM"),
  marksAndNumbers: requiredString("Marks and Numbers"),
  section48: optionalBoolean,
  section48Details: optionalString,
  containerDetails: optionalString,
});

export const importInvoiceRecordSchema = z.object({
  jobNo: optionalString,
  invoiceNo: requiredString("Invoice No"),
  invoiceDate: requiredString("Invoice Date"),
  natureOfPayment: requiredString("Nature of Payment"),
  natureOfTransaction: requiredString("Nature of Transaction"),
  currency: requiredString("Currency"),
  exchangeRate: optionalString,
  invoiceValue: requiredString("Invoice Value"),
  incoterms: requiredString("Incoterms"),
  valuationMethod: optionalString,
  totalInvoice: optionalBoolean,
  useForAllInvoices: optionalBoolean,
  useAsDefaultManufacturer: optionalBoolean,
  supplierName: requiredString("Supplier Name"),
  supplierAddress: optionalString,
  supplierCountry: requiredString("Supplier Country"),
  zipCode: optionalString,
  sellerDetails: optionalString,
  brokerDetails: optionalString,
  thirdParty: optionalBoolean,
  aeo: optionalBoolean,
  svbDetails: optionalString,
  singleFreightAndInsurance: optionalBoolean,
  actualFreight: optionalBoolean,
  charges: z.array(z.object({
    key: z.string(),
    apply: z.boolean(),
    currency: z.string(),
    exchangeRate: z.string(),
    rate: z.string(),
    amount: z.string(),
  })),
});

export const importItemRecordSchema = z.object({
  jobNo: optionalString,
  invoiceId: requiredString("Invoice Serial No"),
  invoiceSerialNo: z.union([z.number(), z.literal("")]),
  invoiceNo: optionalString,
  totalNumberOfProducts: optionalString,
  productSerialNo: optionalString,
  ritcNo: requiredString("RITC No"),
  productDescription: requiredString("Product Description"),
  dutyRate: requiredString("Duty Rate"),
  schemeType: requiredString("Scheme Type"),
  quantity: requiredString("Quantity"),
  unit: requiredString("Unit"),
  unitPrice: requiredString("Unit Price"),
  endUse: requiredString("End Use"),
  countryOfOrigin: requiredString("Country of Origin"),
  cthNo: requiredString("CTH No"),
  cethNo: requiredString("CETH No"),
  schemeCode: optionalString,
  schemeNotification: optionalString,
  notificationSerialNo: optionalString,
  genericDescription: requiredString("Generic Description"),
  foc: optionalBoolean,
  squc: requiredString("SQUC"),
  sqc: requiredString("SQC"),
  duties: z.array(z.object({
    key: z.string(),
    notification: z.string(),
    serialNo: z.string(),
    rate: z.string(),
    amount: z.string(),
    uom: z.string(),
    flag: z.string(),
    manualOverride: z.boolean(),
  })),
  otherDuty: optionalString,
  rsp: optionalString,
  tariff: optionalString,
  antiDumping: optionalString,
  manufacturer: optionalString,
  reImport: optionalString,
  licence: optionalString,
  ftaDetails: optionalString,
  singleWindow: optionalString,
  sez: optionalString,
});

export const importDeclarationRecordSchema = z.object({
  statementType: requiredString("Statement Type"),
  statementCode: requiredString("Statement Code"),
  statementText: optionalString,
  declarationType: requiredString("Declaration Type"),
  declarationNo: optionalString,
  date: optionalString,
  invoiceId: requiredString("Invoice Serial No"),
  invoiceSerialNo: z.union([z.number(), z.literal("")]),
  itemId: requiredString("Item Serial No"),
  itemSerialNo: z.union([z.number(), z.literal("")]),
});

export const importSupportingDocumentRecordSchema = z.object({
  documentTypeCode: requiredString("Document Type Code"),
  irnNo: requiredString("IRN No"),
  drnNo: optionalString,
  issueDate: requiredString("Issue Date"),
  declarationType: optionalString,
  fileType: requiredString("File Type"),
  placeOfIssue: requiredString("Place of Issue"),
  invoiceId: requiredString("Invoice Serial No"),
  invoiceSerialNo: z.union([z.number(), z.literal("")]),
  itemId: requiredString("Item Serial No"),
  itemSerialNo: z.union([z.number(), z.literal("")]),
  expiryDate: optionalString,
  invoiceNo: optionalString,
  icegateId: optionalString,
  attachmentName: optionalString,
  attachmentSize: z.number(),
  attachmentType: optionalString,
  partyCode: optionalString,
  partyName: requiredString("Party Name"),
  partyAddress: requiredString("Address"),
  partyCity: optionalString,
  partyPin: optionalString,
  beneficiaryCode: optionalString,
  beneficiaryName: requiredString("Beneficiary Name"),
  beneficiaryAddress: requiredString("Address"),
  beneficiaryCity: optionalString,
  beneficiaryPin: optionalString,
});
