import type {
  ImportChargeKey,
  ImportDutyKey,
  ImportInvoiceCharge,
  ImportJobDraft,
  ImportJobMainDetails,
} from "./import-job.types";

export const IMPORT_JOB_STORAGE_SCHEMA_VERSION = 1 as const;

export const importChargeLabels: Record<ImportChargeKey, string> = {
  miscellaneous: "Miscellaneous",
  freight: "Freight",
  insurance: "Insurance",
  agency: "Agency",
  loading: "Loading",
  discount: "Discount",
  highSeaSale: "High Sea Sale",
};

export const importDutyLabels: Record<ImportDutyKey, string> = {
  bcd: "BCD / Notification",
  aidc: "AIDC / Notification",
  sws: "SWS Surcharge",
  igst: "IGST Levy",
  igstExemption: "IGST Exemption",
  compensationCess: "Compensation Cess",
  compensationExemption: "Compensation Exemption",
  safeguard: "Safeguard",
  sapta: "SAPTA",
};

export const importChargeKeys = Object.keys(importChargeLabels) as ImportChargeKey[];
export const importDutyKeys = Object.keys(importDutyLabels) as ImportDutyKey[];

export function createEmptyInvoiceCharges(currency = "USD", exchangeRate = "83.00") {
  return importChargeKeys.map<ImportInvoiceCharge>((key) => ({
    key,
    apply: false,
    currency,
    exchangeRate,
    rate: "",
    amount: "",
  }));
}

export function createEmptyDutyRows() {
  return importDutyKeys.map((key) => ({
    key,
    notification: "",
    serialNo: "",
    rate: "",
    amount: "",
    uom: "",
    flag: "",
    manualOverride: false,
  }));
}

export function createEmptyMainDetails(): ImportJobMainDetails {
  return {
    jobNo: "",
    jobDate: "",
    beType: "",
    transportMode: "",
    filingType: "",
    customsHouse: "",
    customsHouseCode: "",
    warehouseCode: "",
    warehouseCustomsSiteId: "",
    numberOfPackages: "",
    packageCode: "",
    grossWeight: "",
    uom: "",
    beNo: "",
    beDate: "",
    examinationDate: "",
    oocDate: "",
    dutyPaidDate: "",
    deliveredDate: "",
    icegateId: "",
    chaPanNo: "",
    atpName: "",
    atpPanNo: "",
    standardIec: "",
    importerName: "",
    iecNo: "",
    branchSerialNo: "",
    importerCategory: "",
    importerType: "",
    importerClass: "",
    address: "",
    city: "",
    state: "",
    pinCode: "",
    adCode: "",
    stateOfOrigin: "",
    gstnType: "",
    taxRegistrationNo: "",
    firstCheck: false,
    greenChannel: false,
    kacchaBe: false,
    provisionalAssessment: false,
    highSeaSale: false,
    exBond: false,
    ucrType: "",
    ucrNo: "",
    paymentMethod: "",
    bondDetails: "",
    certificateDetails: "",
    portOfShipment: "",
    portOfShipmentCode: "",
    countryOfShipment: "",
    countryOfShipmentCode: "",
    portOfOrigin: "",
    portOfOriginCode: "",
    countryOfOrigin: "",
    countryOfOriginCode: "",
    otherDetails: "",
  };
}

export function createBlankImportJobDraft(now = new Date()): ImportJobDraft {
  const timestamp = now.toISOString();

  return {
    id: "import-lab-draft",
    schemaVersion: IMPORT_JOB_STORAGE_SCHEMA_VERSION,
    movementDirection: "IMPORT",
    status: "DRAFT",
    activeTab: "be-main-details",
    createdAt: timestamp,
    updatedAt: timestamp,
    mainDetails: createEmptyMainDetails(),
    igmRecords: [],
    invoiceRecords: [],
    itemRecords: [],
    declarationRecords: [],
    supportingDocumentRecords: [],
    checklistOptions: {
      selectedJobNo: "",
      jobDate: "",
      withDeclaration: true,
      printGeneratedAt: "",
    },
    flatFileOptions: {
      selectedJobNo: "",
      jobDate: "",
      dummyJob: true,
      lastGeneratedAt: "",
      lastChecksum: "",
      lastFlatFile: "",
      lastJson: "",
      lastValidationReport: "",
      history: [],
    },
  };
}

export function createSampleImportJobDraft(now = new Date()): ImportJobDraft {
  const draft = createBlankImportJobDraft(now);
  draft.mainDetails = {
    ...draft.mainDetails,
    jobNo: "LAB-IMP-0001",
    jobDate: "2026-07-31",
    beType: "Home Consumption",
    transportMode: "Sea",
    filingType: "Prior",
    customsHouse: "JNCH Nhava Sheva",
    customsHouseCode: "INNSA1",
    numberOfPackages: "120",
    packageCode: "PKG",
    grossWeight: "24500",
    uom: "KGS",
    icegateId: "TESTCHA01",
    chaPanNo: "AAAAA0000A",
    standardIec: "0312345678",
    importerName: "Demo Importer Private Limited",
    iecNo: "0312345678",
    branchSerialNo: "001",
    importerCategory: "Manufacturer",
    importerType: "Private",
    importerClass: "Regular",
    address: "Plot 42, Industrial Estate",
    city: "Mumbai",
    state: "Maharashtra",
    pinCode: "400001",
    adCode: "0510001",
    stateOfOrigin: "Maharashtra",
    gstnType: "GSTIN",
    taxRegistrationNo: "27AAAAA0000A1Z5",
    paymentMethod: "Transaction",
    portOfShipment: "Shanghai",
    portOfShipmentCode: "CNSHA",
    countryOfShipment: "China",
    countryOfShipmentCode: "CN",
    portOfOrigin: "Shanghai",
    portOfOriginCode: "CNSHA",
    countryOfOrigin: "China",
    countryOfOriginCode: "CN",
  };
  draft.igmRecords = [{
    id: "igm-sample-1",
    serialNo: 1,
    igmNo: "2255667",
    igmDate: "2026-07-26",
    inwardDate: "2026-07-28",
    gatewayPort: "JNPT",
    gatewayMode: "Sea",
    mblNo: "MSCU1234567",
    noMbl: false,
    mblDate: "2026-07-18",
    numberOfPackages: "120",
    packageCode: "PKG",
    twentyFtCount: "1",
    fortyFtCount: "1",
    hblNo: "HBL778899",
    hblDate: "2026-07-19",
    grossWeight: "24500",
    netWeight: "23800",
    uom: "KGS",
    marksAndNumbers: "AS PER PACKING LIST",
    section48: false,
    section48Details: "",
    containerDetails: "MSCU7654321 / 40FT; TLLU1122334 / 20FT",
  }];
  draft.invoiceRecords = [{
    id: "invoice-sample-1",
    serialNo: 1,
    jobNo: "LAB-IMP-0001",
    invoiceNo: "INV-7788",
    invoiceDate: "2026-07-15",
    natureOfPayment: "LC",
    natureOfTransaction: "Sale",
    currency: "USD",
    exchangeRate: "83.20",
    invoiceValue: "12500",
    incoterms: "CIF",
    valuationMethod: "Transaction Value",
    totalInvoice: true,
    useForAllInvoices: true,
    useAsDefaultManufacturer: true,
    supplierName: "Demo Supplier Co",
    supplierAddress: "88 Export Road, Shanghai",
    supplierCountry: "China",
    zipCode: "200000",
    sellerDetails: "Direct seller",
    brokerDetails: "",
    thirdParty: false,
    aeo: false,
    svbDetails: "",
    singleFreightAndInsurance: true,
    actualFreight: true,
    charges: createEmptyInvoiceCharges("USD", "83.20").map((charge) =>
      charge.key === "freight"
        ? { ...charge, apply: true, amount: "250" }
        : charge.key === "insurance"
          ? { ...charge, apply: true, amount: "75" }
          : charge,
    ),
  }];
  draft.itemRecords = [{
    id: "item-sample-1",
    serialNo: 1,
    jobNo: "LAB-IMP-0001",
    invoiceId: "invoice-sample-1",
    invoiceSerialNo: 1,
    invoiceNo: "INV-7788",
    totalNumberOfProducts: "1",
    productSerialNo: "1",
    ritcNo: "85044090",
    productDescription: "Power supply modules",
    dutyRate: "10",
    schemeType: "Normal",
    quantity: "100",
    unit: "NOS",
    unitPrice: "125",
    endUse: "Manufacturing",
    countryOfOrigin: "China",
    cthNo: "85044090",
    cethNo: "85044090",
    schemeCode: "00",
    schemeNotification: "",
    notificationSerialNo: "",
    genericDescription: "Power supplies",
    foc: false,
    squc: "NOS",
    sqc: "100",
    duties: createEmptyDutyRows().map((duty) =>
      duty.key === "bcd"
        ? { ...duty, rate: "10" }
        : duty.key === "sws"
          ? { ...duty, rate: "10" }
          : duty.key === "igst"
            ? { ...duty, rate: "18" }
            : duty,
    ),
    otherDuty: "",
    rsp: "",
    tariff: "",
    antiDumping: "",
    manufacturer: "Demo Supplier Co",
    reImport: "",
    licence: "",
    ftaDetails: "",
    singleWindow: "",
    sez: "",
  }];
  draft.declarationRecords = [{
    id: "declaration-sample-1",
    serialNo: 1,
    statementType: "General",
    statementCode: "DEC001",
    statementText: "Information declared for test workspace only.",
    declarationType: "BE",
    declarationNo: "LAB-DEC-1",
    date: "2026-07-31",
    invoiceId: "invoice-sample-1",
    invoiceSerialNo: 1,
    itemId: "item-sample-1",
    itemSerialNo: 1,
  }];
  draft.supportingDocumentRecords = [{
    id: "document-sample-1",
    serialNo: 1,
    documentTypeCode: "380000",
    irnNo: "IRNTEST7788",
    drnNo: "DRNTEST7788",
    issueDate: "2026-07-15",
    declarationType: "BE",
    fileType: "PDF",
    placeOfIssue: "Shanghai",
    invoiceId: "invoice-sample-1",
    invoiceSerialNo: 1,
    itemId: "item-sample-1",
    itemSerialNo: 1,
    expiryDate: "",
    invoiceNo: "INV-7788",
    icegateId: "TESTCHA01",
    attachmentName: "sample-invoice.pdf",
    attachmentSize: 24812,
    attachmentType: "application/pdf",
    partyCode: "SUP",
    partyName: "Demo Supplier Co",
    partyAddress: "88 Export Road",
    partyCity: "Shanghai",
    partyPin: "200000",
    beneficiaryCode: "IMP",
    beneficiaryName: "Demo Importer Private Limited",
    beneficiaryAddress: "Plot 42, Industrial Estate",
    beneficiaryCity: "Mumbai",
    beneficiaryPin: "400001",
  }];
  draft.checklistOptions = {
    selectedJobNo: draft.mainDetails.jobNo,
    jobDate: draft.mainDetails.jobDate,
    withDeclaration: true,
    printGeneratedAt: "",
  };
  draft.flatFileOptions = {
    ...draft.flatFileOptions,
    selectedJobNo: draft.mainDetails.jobNo,
    jobDate: draft.mainDetails.jobDate,
  };
  return draft;
}
