import type { QuoteListStatus, QuoteRecord } from "./types";

export const quoteViews: Array<{ id: QuoteListStatus; label: string; favorite?: boolean }> = [
  { id: "all", label: "All", favorite: true },
  { id: "draft", label: "Draft" },
  { id: "pending-manager-approval", label: "Pending Manager Approval" },
  { id: "pending-customer-approval", label: "Pending Customer Approval" },
  { id: "customer-approved", label: "Customer Approved" },
  { id: "booking-created", label: "Booking Created" },
];

export const quoteRecords: QuoteRecord[] = [
  {
    id: "quote_101",
    date: "2026-06-18",
    location: "Chennai",
    quoteNumber: "CHN-EST-101",
    customerName: "AG IMPEX PVT LTD",
    status: "draft",
    amount: 670823,
  },
  {
    id: "quote_100",
    date: "2026-06-18",
    location: "Chennai",
    quoteNumber: "CHN-EST-100",
    customerName: "Brilliant Printers Pvt. Ltd.",
    status: "pending-manager-approval",
    amount: 28320,
  },
  {
    id: "quote_099",
    date: "2026-06-18",
    location: "Chennai",
    quoteNumber: "CHN-EST-099",
    customerName: "Pratap Singh",
    status: "pending-customer-approval",
    amount: 656097,
  },
  {
    id: "quote_098",
    date: "2026-06-17",
    location: "Chennai",
    quoteNumber: "CHN-EST-098",
    customerName: "AZT Interiors & Developers",
    status: "draft",
    amount: 83258,
  },
  {
    id: "quote_097",
    date: "2026-06-17",
    location: "Mumbai",
    quoteNumber: "MUM-EST-097",
    customerName: "Bazinga Media Pvt. Ltd.",
    status: "pending-customer-approval",
    amount: 237249,
  },
  {
    id: "quote_096",
    date: "2026-06-17",
    location: "Delhi",
    quoteNumber: "DEL-EST-096",
    customerName: "PUREVIDA PROJECTS",
    status: "pending-customer-approval",
    amount: 369442,
  },
  {
    id: "quote_095",
    date: "2026-06-16",
    location: "Chennai",
    quoteNumber: "CHN-EST-095",
    customerName: "Inch Trading & Sourcing Co.",
    status: "customer-approved",
    amount: 101930,
  },
  {
    id: "quote_094",
    date: "2026-06-16",
    location: "Kolkata",
    quoteNumber: "KOL-EST-094",
    customerName: "Hi Tech Engineers (India)",
    status: "booking-created",
    amount: 13238,
  },
  {
    id: "quote_093",
    date: "2026-06-16",
    location: "Chennai",
    quoteNumber: "CHN-EST-093",
    customerName: "Gable Top Packaging Private Limited",
    status: "draft",
    amount: 16053,
  },
  {
    id: "quote_092",
    date: "2026-06-16",
    location: "Mundra",
    quoteNumber: "MUN-EST-092",
    customerName: "Mohit Chauhan",
    status: "draft",
    amount: 14160,
  },
  {
    id: "quote_091",
    date: "2026-06-15",
    location: "Chennai",
    quoteNumber: "CHN-EST-091",
    customerName: "Suresh Meganathan",
    status: "pending-manager-approval",
    amount: 312405,
  },
  {
    id: "quote_090",
    date: "2026-06-15",
    location: "Chennai",
    quoteNumber: "CHN-EST-090",
    customerName: "Blush Beauty",
    status: "pending-customer-approval",
    amount: 68600,
  },
];
